name: Integration Tests
on:
    push:
    pull_request:
    schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php73-fpm
            MAGENTO_VERSION: 2.3.7-p3
          - PHP_VERSION: php74-fpm
            MAGENTO_VERSION: 2.4.0
          - PHP_VERSION: php81-fpm
            MAGENTO_VERSION: 2.4.5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Public repository
      - uses: actions/checkout@v2
        if: "!contains(github.repository, 'magmodules')"
        with:
          repository: mollie/magento2
          path: mollie-base
          ref: master

      # Internal repository
      - uses: actions/checkout@v2
        if: "contains(github.repository, 'magmodules')"
        with:
          repository: magmodules/mollie-magento2
          path: mollie-base
          ssh-key: ${{ secrets.MAGMODULES_MOLLIE_MAGENTO2_KEY }}

      - name: Start Docker
        run: docker run --detach --name magento-project-community-edition michielgerritsen/magento-project-community-edition:${{ matrix.PHP_VERSION }}-magento${{ matrix.MAGENTO_VERSION }}

      - name: Remove version from composer.json
        run: sed -i '/version/d' ./composer.json && sed -i '/version/d' ./mollie-base/composer.json

      - name: Upload the code into the docker container
        run: docker cp $(pwd)/mollie-base/ magento-project-community-edition:/data/extensions/mollie-magento2/ && rm -rf mollie-base/ && docker cp $(pwd)/. magento-project-community-edition:/data/extensions/mollie-magento2-multishipping/

      - name: Install Mollie and Mollie Multishipping extensions
        run: docker exec magento-project-community-edition composer require mollie/magento2:"dev-master as 2.99.99" mollie/magento2-multishipping:@dev -vvv

      - name: Enable developer mode
        run: docker exec magento-project-community-edition php bin/magento deploy:mode:set developer

      - name: Run tests
        run: docker exec magento-project-community-edition bash -c "cd /data/dev/tests/integration/ && /data/vendor/bin/phpunit -c /data/dev/tests/integration/phpunit.xml"
